version: '3'
services:
  redis:
    image: 'redis:6.2.1-alpine'
  api: 
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes: 
      - /api/node_modules
      - ./api:/app
    environment: 
      - NEST_APP_DB_URL
      - NEST_JWT_SECRET
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_CACHE_TTL
      - REDIS_MAX_ITEM_IN_CACHE
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - api
