version: '3'
services:
  redis:
    image: 'redis:6.2.1-alpine'
  api: 
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes: 
      - /app/node_modules
      - ./api:/app
    environment: 
      - NEST_APP_DB_URL
      - NEST_JWT_SECRET
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - api
