
version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
   steps:
     - checkout
     - setup_remote_docker:
        version: 19.03.13
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: docker build -t jfourdachon/nest-graphql -f ./api/Dockerfile ./api

     - run: docker run -e CI=true jfourdachon/nest-graphql yarn test
