version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    working_directory: ~/api
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: ~/backend_api
          cache-path: node_modules
          override-ci-command: npm i
workflows:
  node-tests:
    jobs:
      - node/test
